#define WIN32_LEAN_AND_MEAN
#include "report_ui.h"
#include "theme.h"
#include "search_model.h"
#include <windowsx.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>
#include <limits.h>
static const wchar_t report_class[]=L"S14ModManager.TurnCards.v1";
static int px(const S14ReportUI *u,int n){return MulDiv(n,u->scale,96);}
static int dp(const S14ReportUI *u,int n){return MulDiv(n,96,u->scale);}
static void fill(HDC dc,RECT r,COLORREF c){HBRUSH b=CreateSolidBrush(c);FillRect(dc,&r,b);DeleteObject(b);}
static void roundbox(S14ReportUI *u,HDC dc,RECT r,COLORREF bg,COLORREF edge,int radius){HBRUSH brush=CreateSolidBrush(bg);HPEN pen=CreatePen(PS_SOLID,px(u,1),edge);HGDIOBJ a=SelectObject(dc,brush),b=SelectObject(dc,pen);RoundRect(dc,r.left,r.top,r.right,r.bottom,px(u,radius),px(u,radius));SelectObject(dc,a);SelectObject(dc,b);DeleteObject(brush);DeleteObject(pen);}
static void text(S14ReportUI *u,HDC dc,HFONT font,COLORREF color,RECT r,const wchar_t *value,UINT flags){(void)u;HGDIOBJ old=SelectObject(dc,font);SetTextColor(dc,color);DrawTextW(dc,value,-1,&r,flags|DT_NOPREFIX);SelectObject(dc,old);}
static void number(uint64_t n,wchar_t out[40]){wchar_t raw[32];swprintf(raw,32,L"%llu",(unsigned long long)n);size_t length=wcslen(raw),at=0;for(size_t i=0;i<length;i++){if(i&&(length-i)%3==0)out[at++]=L',';out[at++]=raw[i];}out[at]=0;}
static const wchar_t *period(const unsigned char c[6]){return c[3]<=10?L"上旬":c[3]<=20?L"中旬":L"下旬";}
static void date_text(const unsigned char c[6],wchar_t out[64],int day){int year=c[0]+256*c[1];if(year>0&&c[2]>=1&&c[2]<=12&&c[3]>=1&&c[3]<=30){if(day)swprintf(out,64,L"%d月%d日",c[2],c[3]);else swprintf(out,64,L"%d 年 · %d 月%ls",year,c[2],period(c));}else wcscpy(out,L"本回合");}
static HFONT font(S14ReportUI *u,int size,int weight,const wchar_t *face){return CreateFontW(-px(u,size),0,0,0,weight,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,face);}
static int fonts(S14ReportUI *u,int scale){HFONT *list[]={&u->title,&u->name,&u->body,&u->small,&u->number};for(int i=0;i<5;i++)if(*list[i]){DeleteObject(*list[i]);*list[i]=NULL;}u->scale=scale;u->title=font(u,28,FW_NORMAL,L"SimSun");u->name=font(u,21,FW_SEMIBOLD,L"SimSun");u->body=font(u,13,FW_NORMAL,L"Microsoft YaHei UI");u->small=font(u,11,FW_NORMAL,L"Microsoft YaHei UI");u->number=font(u,25,FW_NORMAL,L"Georgia");return u->title&&u->name&&u->body&&u->small&&u->number;}
static int outcome(const S14ReportActor *a){return a->defeats||a->captured?3:a->captures?2:a->routs||a->wins?1:0;}
static COLORREF tone(int state){return state==3?RGB(160,105,95):state==2?RGB(164,123,63):state==1?RGB(81,116,96):S14_MUTED;}
static COLORREF wash(int state){return state==3?RGB(246,234,228):state==2?RGB(246,238,219):state==1?RGB(237,243,234):RGB(242,239,232);}
static const wchar_t *badge(const S14ReportActor *a){return a->defeats?L"所部覆灭":a->captured?L"遭敌俘虏":a->captures?L"擒获敌将":a->routs?L"击破敌军":a->wins?L"单挑制胜":a->losses?L"单挑败北":L"参与交战";}
static void layout(S14ReportUI *u){int width=dp(u,u->width);u->columns=width>=820?3:width>=590?2:1;u->body_top=px(u,155);u->body_bottom=u->height-px(u,49);u->card_height=px(u,225);u->card_top=u->body_top+px(u,129);int rows=(u->battle.actor_count+u->columns-1)/u->columns;u->event_top=u->card_top+rows*(u->card_height+px(u,12))+px(u,20);u->raw_top=u->event_top+px(u,27)+u->important_count*px(u,65)+px(u,18);u->content_height=u->raw_top-u->body_top+px(u,38);}
static RECT card_rect(S14ReportUI *u,int index){int gap=px(u,12),left=px(u,26),width=(u->width-2*left-(u->columns-1)*gap)/u->columns;int col=index%u->columns,row=index/u->columns;return(RECT){left+col*(width+gap),u->card_top+row*(u->card_height+gap)-u->scroll,left+col*(width+gap)+width,u->card_top+row*(u->card_height+gap)+u->card_height-u->scroll};}
static int in(RECT r,int x,int y){return x>=r.left&&x<r.right&&y>=r.top&&y<r.bottom;}
static int maximum(S14ReportUI *u){int visible=u->body_bottom-u->body_top;int height=u->detail?u->detail_height:u->content_height;return height>visible?height-visible:0;}
static void clamp(S14ReportUI *u){int *s=u->detail?&u->detail_scroll:&u->scroll;int max=maximum(u);if(*s<0)*s=0;if(*s>max)*s=max;}
static int measured(S14ReportUI *u,HDC dc,const wchar_t *s,int width){RECT r={0,0,width,0};HGDIOBJ old=SelectObject(dc,u->body);DrawTextW(dc,s,-1,&r,DT_WORDBREAK|DT_NOPREFIX|DT_CALCRECT);SelectObject(dc,old);return r.bottom>px(u,18)?r.bottom:px(u,18);}
static void draw_card(S14ReportUI *u,HDC dc,int index){
    const S14ReportActor *a=&u->battle.actors[index];RECT r=card_rect(u,index);if(r.bottom<u->body_top||r.top>u->body_bottom)return;int state=outcome(a);COLORREF color=tone(state);roundbox(u,dc,r,S14_CARD,color,12);
    RECT bar={r.left+px(u,1),r.top+px(u,1),r.right-px(u,1),r.top+px(u,29)};fill(dc,bar,wash(state));RECT title={r.left+px(u,13),r.top+px(u,4),r.right-px(u,13),r.top+px(u,26)};text(u,dc,u->small,color,title,badge(a),DT_SINGLELINE|DT_VCENTER);
    wchar_t count[48];if(a->defeats)swprintf(count,48,L"覆灭 %d 次",a->defeats);else if(a->captured)swprintf(count,48,L"被俘 %d 次",a->captured);else if(a->captures)swprintf(count,48,L"擒获 %d 人",a->captures);else if(a->routs)swprintf(count,48,L"击溃 %d 队",a->routs);else if(a->wins)swprintf(count,48,L"获胜 %d 次",a->wins);else count[0]=0;text(u,dc,u->small,color,title,count,DT_RIGHT|DT_SINGLELINE|DT_VCENTER);
    RECT portrait={r.left+px(u,13),r.top+px(u,43),r.left+px(u,80),r.top+px(u,126)};roundbox(u,dc,portrait,RGB(236,229,216),RGB(211,198,178),8);
    int save=SaveDC(dc);HRGN region=CreateRoundRectRgn(portrait.left,portrait.top,portrait.right,portrait.bottom,px(u,8),px(u,8));ExtSelectClipRgn(dc,region,RGN_AND);DeleteObject(region);if(!s14_portrait_draw(u->portraits,a->portrait,dc,&portrait,state==3))text(u,dc,u->name,color,portrait,a->name,DT_CENTER|DT_VCENTER|DT_SINGLELINE);RestoreDC(dc,save);
    if(state){RECT seal={portrait.right-px(u,23),portrait.bottom-px(u,20),portrait.right+px(u,5),portrait.bottom+px(u,4)};roundbox(u,dc,seal,color,S14_CARD,5);text(u,dc,u->small,S14_CARD,seal,state==3?L"败":state==2?L"擒":L"破",DT_CENTER|DT_VCENTER|DT_SINGLELINE);}
    RECT name={portrait.right+px(u,14),r.top+px(u,43),r.right-px(u,12),r.top+px(u,71)};text(u,dc,u->name,S14_INK,name,a->name,DT_SINGLELINE|DT_VCENTER|DT_END_ELLIPSIS);RECT place=name;place.top=r.top+px(u,75);place.bottom=r.top+px(u,95);text(u,dc,u->small,S14_MUTED,place,a->place[0]?a->place:L"地点未记录",DT_SINGLELINE|DT_END_ELLIPSIS);
    wchar_t chips[128]={0};size_t at=0;
#define CHIP(...) do {int n=swprintf(chips+at,128-at,__VA_ARGS__);if(n>0)at+=(size_t)n;}while(0)
    if(a->routs)CHIP(L"破敌 %d  ",a->routs);if(a->wins)CHIP(L"单挑胜 %d  ",a->wins);if(a->losses)CHIP(L"单挑败 %d  ",a->losses);if(a->captures)CHIP(L"擒获 %d",a->captures);if(!chips[0]&&a->effects)CHIP(L"战法效果 %d",a->effects);if(!chips[0]&&a->defeats)CHIP(L"所部覆灭 %d",a->defeats);
#undef CHIP
    RECT chip={name.left,r.top+px(u,102),name.right,r.top+px(u,124)};text(u,dc,u->small,color,chip,chips,DT_WORDBREAK);
    const wchar_t *labels[]={L"斩敌总数",L"士卒折损",L"杀损比值"};wchar_t values[3][40];number(a->inflicted,values[0]);number(a->lost,values[1]);s14_report_ratio(a->inflicted,a->lost,values[2],40);for(int i=0;i<3;i++){int x=r.left+px(u,13)+(r.right-r.left-px(u,26))*i/3;RECT label={x,r.top+px(u,143),x+(r.right-r.left-px(u,26))/3,r.top+px(u,161)};text(u,dc,u->small,S14_MUTED,label,labels[i],DT_SINGLELINE);label.top=r.top+px(u,164);label.bottom=r.top+px(u,191);text(u,dc,u->name,i==0||(state==3&&i==1)?color:S14_INK,label,values[i],DT_SINGLELINE|DT_VCENTER);}
    RECT note={r.left+px(u,1),r.bottom-px(u,29),r.right-px(u,1),r.bottom-px(u,1)};fill(dc,note,wash(state));note.left+=px(u,12);note.right-=px(u,12);wchar_t summary[80];swprintf(summary,80,L"击伤 %d · 吸收伤兵 %llu",a->injuries,(unsigned long long)a->absorbed);text(u,dc,u->small,color,note,summary,DT_SINGLELINE|DT_VCENTER);text(u,dc,u->small,color,note,L"详情 ›",DT_SINGLELINE|DT_VCENTER|DT_RIGHT);
}
static const wchar_t *kind(const S14ReportLine *e){return e->kind==S14_REPORT_ROUT?L"部队击溃":e->kind==S14_REPORT_DUEL?L"单挑战事":e->kind==S14_REPORT_CAPTURE?L"擒获敌将":e->kind==S14_REPORT_INJURY?L"击伤敌将":e->kind==S14_REPORT_FIRE?L"起火事件":e->kind==S14_REPORT_SKILL?L"战法效果":L"交战记录";}
static void line_block(S14ReportUI *u,HDC dc,const S14ReportLine *e,int y,int height,int detail){
    RECT r={px(u,26),y,u->width-px(u,26),y+height};if(r.bottom<u->body_top||r.top>u->body_bottom)return;roundbox(u,dc,r,S14_CARD,S14_BORDER,8);wchar_t date[64];date_text(e->clock,date,1);RECT when={r.left+px(u,12),r.top+px(u,9),r.left+px(u,75),r.top+px(u,27)};text(u,dc,u->small,S14_MUTED,when,date,DT_SINGLELINE);RECT label={when.right,r.top+px(u,9),when.right+px(u,70),r.top+px(u,27)};text(u,dc,u->small,e->verified?S14_SUCCESS:S14_MUTED,label,kind(e),DT_SINGLELINE);RECT where={label.right+px(u,10),r.top+px(u,9),r.right-px(u,12),r.top+px(u,27)};text(u,dc,u->small,S14_MUTED,where,e->place[0]?e->place:L"地点未记录",DT_SINGLELINE|DT_END_ELLIPSIS|DT_RIGHT);RECT message={r.left+px(u,12),r.top+px(u,29),r.right-px(u,12),r.bottom-px(u,7)};text(u,dc,u->body,S14_INK,message,e->text,detail?DT_WORDBREAK:DT_SINGLELINE|DT_END_ELLIPSIS);
}
static void draw_detail(S14ReportUI *u,HDC dc){
    RECT panel={px(u,26),u->body_top+px(u,9),u->width-px(u,26),u->body_bottom-px(u,7)};roundbox(u,dc,panel,S14_PAPER,S14_BORDER,12);const wchar_t *titles[]={L"本回合探索明细",L"发现武将 · 探索明细",L"获得名品 · 探索明细",L"获得战法书 · 探索明细",L"获得金钱 · 探索明细"};const S14ReportActor *actor=u->detail==2&&u->detail_actor>=0&&u->detail_actor<u->battle.actor_count?&u->battle.actors[u->detail_actor]:NULL;
    wchar_t heading[96];if(actor)swprintf(heading,96,L"%ls · 本回合战绩",actor->name);else wcscpy(heading,titles[u->detail_filter<0?0:u->detail_filter]);RECT title={panel.left+px(u,17),panel.top+px(u,12),panel.right-px(u,85),panel.top+px(u,43)};text(u,dc,u->name,S14_INK,title,heading,DT_VCENTER|DT_SINGLELINE);u->detail_close=(RECT){panel.right-px(u,73),panel.top+px(u,13),panel.right-px(u,13),panel.top+px(u,42)};roundbox(u,dc,u->detail_close,S14_CARD,S14_BORDER,6);text(u,dc,u->small,S14_MUTED,u->detail_close,L"返回",DT_CENTER|DT_VCENTER|DT_SINGLELINE);
    int content_top=panel.top+px(u,59),y=content_top-u->detail_scroll;int saved=SaveDC(dc);IntersectClipRect(dc,panel.left+px(u,1),content_top,panel.right-px(u,1),panel.bottom-px(u,8));int rows=0;
    if(actor){wchar_t summary[240],ratio[40];s14_report_ratio(actor->inflicted,actor->lost,ratio,40);swprintf(summary,240,L"斩敌 %llu · 折损 %llu · 杀损比 %ls\n破敌 %d · 覆灭 %d · 单挑制胜 %d · 单挑败北 %d · 擒获 %d · 被俘 %d",(unsigned long long)actor->inflicted,(unsigned long long)actor->lost,ratio,actor->routs,actor->defeats,actor->wins,actor->losses,actor->captures,actor->captured);int h=measured(u,dc,summary,panel.right-panel.left-px(u,34))+px(u,14);RECT sr={panel.left+px(u,17),y,panel.right-px(u,17),y+h};text(u,dc,u->body,tone(outcome(actor)),sr,summary,DT_WORDBREAK);y+=h;for(int i=0;i<u->battle.line_count;i++){const S14ReportLine *e=&u->battle.lines[i];if(e->actor!=actor->id&&e->target!=actor->id)continue;int height=measured(u,dc,e->text,u->width-px(u,102))+px(u,49);line_block(u,dc,e,y,height,1);y+=height+px(u,8);rows++;}}
    else{for(int i=0;i<u->search_data.line_count;i++){const S14ReportSearchLine *e=&u->search_data.lines[i];if(u->detail_filter>=0&&e->type!=u->detail_filter)continue;int h=measured(u,dc,e->text,panel.right-panel.left-px(u,34))+px(u,22);RECT row={panel.left+px(u,17),y,panel.right-px(u,17),y+h};text(u,dc,u->body,e->type==S14_SEARCH_NOTHING?RGB(160,105,95):S14_INK,row,e->text,DT_WORDBREAK);y+=h+px(u,6);rows++;}}
    if(!rows){RECT empty={panel.left+px(u,17),y,panel.right-px(u,17),y+px(u,64)};text(u,dc,u->body,S14_MUTED,empty,u->detail==2?L"本回合没有该武将的逐条记录。":!u->search_data.available?L"本回合没有已采集的探索记录。":L"本回合没有此类收获。",DT_WORDBREAK);y+=px(u,64);}RestoreDC(dc,saved);u->detail_height=y+u->detail_scroll-content_top+px(u,79);clamp(u);
}
void s14_report_ui_paint(S14ReportUI *u,HDC dc){
    SetBkMode(dc,TRANSPARENT);fill(dc,(RECT){0,0,u->width,u->height},S14_PAPER);fill(dc,(RECT){px(u,26),0,u->width-px(u,26),px(u,3)},S14_ACCENT);RECT header={px(u,26),px(u,20),u->width-px(u,70),px(u,70)};text(u,dc,u->title,S14_INK,header,L"回合总结",DT_SINGLELINE|DT_VCENTER);RECT sub={px(u,26),px(u,71),u->width-px(u,70),px(u,87)};text(u,dc,u->small,S14_MUTED,sub,L"天下归心 · 自势力战事与探索",DT_SINGLELINE);
    wchar_t date[64];date_text(u->battle.end_clock,date,0);RECT date_r={u->width/2,px(u,28),u->width-px(u,77),px(u,48)};text(u,dc,u->body,S14_INK,date_r,date,DT_SINGLELINE|DT_RIGHT);wchar_t force[96];swprintf(force,96,L"%ls · 本回合记录",u->force_name[0]?u->force_name:L"自势力");date_r.top=px(u,54);date_r.bottom=px(u,73);text(u,dc,u->small,S14_MUTED,date_r,force,DT_SINGLELINE|DT_RIGHT);u->close=(RECT){u->width-px(u,59),px(u,24),u->width-px(u,25),px(u,58)};roundbox(u,dc,u->close,RGB(240,236,228),RGB(240,236,228),34);text(u,dc,u->name,S14_MUTED,u->close,L"×",DT_CENTER|DT_VCENTER|DT_SINGLELINE);
    RECT exploration={0,px(u,100),u->width,px(u,155)};fill(dc,exploration,S14_CARD);u->search[0]=(RECT){px(u,26),px(u,105),px(u,133),px(u,150)};text(u,dc,u->body,RGB(139,106,68),u->search[0],L"探索所得 ›",DT_SINGLELINE|DT_VCENTER);const wchar_t *labels[]={L"获得金钱",L"发现武将",L"获得名品",L"获得战法书"};int totals[]={u->search_data.money,u->search_data.people,u->search_data.items,u->search_data.books};int left=px(u,137),cell=(u->width-left-px(u,26))/4;
    for(int i=0;i<4;i++){u->search[i+1]=(RECT){left+i*cell,px(u,102),left+(i+1)*cell,px(u,153)};RECT r=u->search[i+1];r.left+=px(u,6);r.top+=px(u,4);r.bottom=r.top+px(u,17);text(u,dc,u->small,S14_MUTED,r,labels[i],DT_CENTER|DT_SINGLELINE);wchar_t value[40];if(u->search_data.available)number((uint64_t)totals[i],value);else wcscpy(value,L"—");r.top+=px(u,19);r.bottom+=px(u,29);text(u,dc,u->number,RGB(141,109,66),r,value,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}
    layout(u);int saved=SaveDC(dc);IntersectClipRect(dc,0,u->body_top,u->width,u->body_bottom);if(u->detail)draw_detail(u,dc);else{
        int y=u->body_top+px(u,16)-u->scroll;RECT heading={px(u,26),y,u->width-px(u,26),y+px(u,24)};text(u,dc,u->body,S14_INK,heading,L"战斗纪要",DT_SINGLELINE|DT_VCENTER);wchar_t participants[80];swprintf(participants,80,L"%d 位武将参与 · 自势力",u->battle.actor_count);text(u,dc,u->small,S14_MUTED,heading,participants,DT_SINGLELINE|DT_VCENTER|DT_RIGHT);const wchar_t *metric_labels[]={L"斩敌总数（含伤兵）",L"士卒折损",L"破敌次数",L"所部覆灭",L"吸收伤兵"};uint64_t values[]={u->battle.inflicted,u->battle.lost,(uint64_t)u->battle.routs,(uint64_t)u->battle.defeats,u->battle.absorbed};RECT metrics={px(u,26),y+px(u,35),u->width-px(u,26),y+px(u,101)};roundbox(u,dc,metrics,RGB(244,241,233),S14_BORDER,10);int mcell=(metrics.right-metrics.left)/5;
        for(int i=0;i<5;i++){RECT r={metrics.left+i*mcell+px(u,12),metrics.top+px(u,9),metrics.left+(i+1)*mcell-px(u,6),metrics.top+px(u,26)};text(u,dc,u->small,S14_MUTED,r,metric_labels[i],DT_SINGLELINE|DT_END_ELLIPSIS);r.top+=px(u,18);r.bottom=metrics.bottom-px(u,7);wchar_t value[40];if(u->battle.available&&u->battle.force>0)number(values[i],value);else wcscpy(value,L"—");text(u,dc,u->number,i==0?S14_ACCENT:i==2?S14_SUCCESS:S14_INK,r,value,DT_SINGLELINE);}
        for(int i=0;i<u->battle.actor_count;i++)draw_card(u,dc,i);if(!u->battle.actor_count){RECT empty={px(u,26),u->card_top-u->scroll,u->width-px(u,26),u->card_top-u->scroll+px(u,27)};text(u,dc,u->body,S14_MUTED,empty,!u->battle.available?L"本回合战斗记录未开启或未采集到完整数据。":!u->battle.force?L"无法确认玩家势力，本页不代表零战绩。":L"本回合未观察到自势力相关战斗。",DT_WORDBREAK);u->event_top+=px(u,40);u->raw_top+=px(u,40);u->content_height+=px(u,40);}
        RECT events_title={px(u,26),u->event_top-u->scroll,u->width-px(u,26),u->event_top-u->scroll+px(u,20)};text(u,dc,u->small,S14_MUTED,events_title,L"重要战事 · 日期与城市／府",DT_SINGLELINE);for(int i=0;i<u->important_count;i++)line_block(u,dc,&u->battle.lines[u->important[i]],u->event_top+px(u,27)+i*px(u,65)-u->scroll,px(u,57),0);if(!u->important_count){events_title.top+=px(u,25);events_title.bottom+=px(u,25);text(u,dc,u->small,S14_MUTED,events_title,L"本回合没有已记录的重要战事。",DT_SINGLELINE);u->raw_top+=px(u,25);u->content_height+=px(u,25);}
        wchar_t raw_label[80];swprintf(raw_label,80,u->expanded?L"▾ 收起逐条战斗明细 · %d 条":L"▸ 展开逐条战斗明细 · %d 条",u->battle.line_count);RECT raw={px(u,26),u->raw_top-u->scroll,u->width-px(u,26),u->raw_top-u->scroll+px(u,27)};text(u,dc,u->small,S14_ACCENT,raw,raw_label,DT_SINGLELINE|DT_VCENTER);if(u->expanded){int at=u->raw_top+px(u,38);for(int i=0;i<u->battle.line_count;i++){const S14ReportLine *e=&u->battle.lines[i];int h=measured(u,dc,e->text,u->width-px(u,76))+px(u,49);line_block(u,dc,e,at-u->scroll,h,1);at+=h+px(u,8);}u->content_height=at-u->body_top+px(u,18);}clamp(u);
    }RestoreDC(dc,saved);fill(dc,(RECT){0,u->body_bottom,u->width,u->height},S14_PAPER);fill(dc,(RECT){px(u,26),u->body_bottom,u->width-px(u,26),u->body_bottom+px(u,1)},S14_BORDER);RECT footer={px(u,26),u->body_bottom+px(u,10),u->width-px(u,150),u->height-px(u,8)};text(u,dc,u->small,u->battle.incomplete||u->search_data.truncated?S14_ERROR:S14_MUTED,footer,u->battle.incomplete||u->search_data.truncated?L"本回合采集不完整 · 已记录的结果仍可查阅":L"斩敌包含伤兵 · 点击探索数字／武将查看详情",DT_SINGLELINE|DT_VCENTER|DT_END_ELLIPSIS);u->done=(RECT){u->width-px(u,130),u->body_bottom+px(u,9),u->width-px(u,26),u->height-px(u,9)};roundbox(u,dc,u->done,S14_ACCENT,S14_ACCENT,7);text(u,dc,u->body,S14_CARD,u->done,L"阅毕 · 关闭",DT_CENTER|DT_VCENTER|DT_SINGLELINE);
    int max=maximum(u),scroll=u->detail?u->detail_scroll:u->scroll;u->thumb=(RECT){0};if(max>0){int top=u->body_top+px(u,8),height=u->body_bottom-top-px(u,8),thumb=height*height/(height+max);if(thumb<px(u,24))thumb=px(u,24);int at=top+MulDiv(scroll,height-thumb,max);u->thumb=(RECT){u->width-px(u,12),at,u->width-px(u,6),at+thumb};roundbox(u,dc,u->thumb,RGB(197,185,167),RGB(197,185,167),6);}
}
void s14_report_ui_hide(S14ReportUI *u){if(!u)return;u->visible=0;u->detail=0;u->dragging=0;if(u->window){ReleaseCapture();ShowWindow(u->window,SW_HIDE);}}
void s14_report_ui_clear(S14ReportUI *u){if(!u)return;s14_report_ui_hide(u);s14_report_search_free(&u->search_data);s14_report_battle_free(&u->battle);free(u->important);u->important=NULL;u->important_count=0;}
static void scroll_by(S14ReportUI *u,int delta){int *scroll=u->detail?&u->detail_scroll:&u->scroll;*scroll+=delta;clamp(u);InvalidateRect(u->window,NULL,FALSE);}
static LRESULT CALLBACK report_proc(HWND window,UINT msg,WPARAM wp,LPARAM lp){
    S14ReportUI *u=(S14ReportUI*)GetWindowLongPtrW(window,GWLP_USERDATA);if(msg==WM_NCCREATE){u=((CREATESTRUCTW*)lp)->lpCreateParams;SetWindowLongPtrW(window,GWLP_USERDATA,(LONG_PTR)u);}if(!u)return DefWindowProcW(window,msg,wp,lp);
    if(msg==WM_PAINT){PAINTSTRUCT ps;HDC dc=BeginPaint(window,&ps),buffer=CreateCompatibleDC(dc);HBITMAP image=CreateCompatibleBitmap(dc,u->width,u->height);HGDIOBJ old=SelectObject(buffer,image);s14_report_ui_paint(u,buffer);BitBlt(dc,0,0,u->width,u->height,buffer,0,0,SRCCOPY);SelectObject(buffer,old);DeleteObject(image);DeleteDC(buffer);EndPaint(window,&ps);return 0;}if(msg==WM_ERASEBKGND)return 1;if(msg==WM_CLOSE){s14_report_ui_hide(u);return 0;}if(msg==WM_SIZE){u->width=LOWORD(lp);u->height=HIWORD(lp);layout(u);clamp(u);InvalidateRect(window,NULL,FALSE);return 0;}if(msg==WM_MOUSEWHEEL){scroll_by(u,-GET_WHEEL_DELTA_WPARAM(wp)*px(u,65)/WHEEL_DELTA);return 0;}
    if(msg==WM_KEYDOWN){if(wp==VK_ESCAPE){if(u->detail){u->detail=0;InvalidateRect(window,NULL,FALSE);}else s14_report_ui_hide(u);}else if(wp==VK_DOWN||wp==VK_NEXT)scroll_by(u,px(u,wp==VK_DOWN?40:300));else if(wp==VK_UP||wp==VK_PRIOR)scroll_by(u,-px(u,wp==VK_UP?40:300));else if(wp==VK_HOME)scroll_by(u,-INT_MAX/2);else if(wp==VK_END)scroll_by(u,INT_MAX/2);return 0;}
    if(msg==WM_LBUTTONDOWN){int x=GET_X_LPARAM(lp),y=GET_Y_LPARAM(lp);if(in(u->thumb,x,y)){u->dragging=1;u->drag_y=y;u->drag_start=u->detail?u->detail_scroll:u->scroll;SetCapture(window);}return 0;}if(msg==WM_MOUSEMOVE&&u->dragging){int track=u->body_bottom-u->body_top-px(u,16)-(u->thumb.bottom-u->thumb.top);if(track>0){int *scroll=u->detail?&u->detail_scroll:&u->scroll;*scroll=u->drag_start+MulDiv(GET_Y_LPARAM(lp)-u->drag_y,maximum(u),track);clamp(u);InvalidateRect(window,NULL,FALSE);}return 0;}
    if(msg==WM_LBUTTONUP){if(u->dragging){u->dragging=0;ReleaseCapture();return 0;}int x=GET_X_LPARAM(lp),y=GET_Y_LPARAM(lp);if(in(u->close,x,y)||in(u->done,x,y)){s14_report_ui_hide(u);return 0;}if(u->detail&&in(u->detail_close,x,y)){u->detail=0;InvalidateRect(window,NULL,FALSE);return 0;}for(int i=0;i<5;i++)if(in(u->search[i],x,y)){const int categories[]={-1,4,1,2,3};u->detail=1;u->detail_filter=categories[i];u->detail_scroll=0;InvalidateRect(window,NULL,FALSE);return 0;}if(u->detail)return 0;if(y>=u->body_top&&y<u->body_bottom){for(int i=0;i<u->battle.actor_count;i++)if(in(card_rect(u,i),x,y)){u->detail=2;u->detail_actor=i;u->detail_scroll=0;InvalidateRect(window,NULL,FALSE);return 0;}if(y>=u->raw_top-u->scroll&&y<u->raw_top-u->scroll+px(u,28)){u->expanded=!u->expanded;InvalidateRect(window,NULL,FALSE);return 0;}}return 0;}
    if(msg==WM_TIMER){if(u->visible)InvalidateRect(window,NULL,FALSE);return 0;}return DefWindowProcW(window,msg,wp,lp);
}
static int create(S14ReportUI *u,HINSTANCE instance,HWND owner){WNDCLASSEXW wc={.cbSize=sizeof(wc),.lpfnWndProc=report_proc,.hInstance=instance,.hCursor=LoadCursorW(NULL,IDC_ARROW),.lpszClassName=report_class};if(!RegisterClassExW(&wc)&&GetLastError()!=ERROR_CLASS_ALREADY_EXISTS)return 0;UINT scale=owner?GetDpiForWindow(owner):96;if(scale<96||scale>384)scale=96;if(!fonts(u,(int)scale))return 0;u->window=CreateWindowExW(WS_EX_TOOLWINDOW,report_class,L"天下归心 · 回合总结",WS_POPUP|WS_CLIPCHILDREN,0,0,px(u,1100),px(u,790),owner,NULL,instance,u);return u->window!=NULL;}
static void identities(S14ReportUI *u){if(!u->base||!u->battle.world)return;for(int i=0;i<u->battle.actor_count;i++)u->battle.actors[i].portrait=s14_portrait_identity(u->base,u->battle.world,u->battle.actors[i].id);if(u->battle.force<=0||u->battle.force>51)return;HANDLE process=GetCurrentProcess();SIZE_T got;uintptr_t record=0,person=0;unsigned short leader=0;unsigned char raw[54];if(ReadProcessMemory(process,(void*)(u->battle.world+0xdca0+(size_t)u->battle.force*8),&record,8,&got)&&got==8&&record&&ReadProcessMemory(process,(void*)(record+0x10),&leader,2,&got)&&got==2&&leader>0&&leader<=6000&&ReadProcessMemory(process,(void*)(u->battle.world+0x148+(size_t)leader*8),&person,8,&got)&&got==8&&person&&ReadProcessMemory(process,(void*)person,raw,sizeof(raw),&got)&&got==sizeof(raw)){uintptr_t vt=0;memcpy(&vt,raw,8);if(vt==u->base+0x12a00d0){wchar_t first[10]={0},second[10]={0};memcpy(first,raw+0x12,18);memcpy(second,raw+0x24,18);swprintf(u->force_name,32,L"%ls%ls势力",first,second);}}}
int s14_report_ui_reopen(S14ReportUI *u){if(!u||!u->window||(!u->search_data.available&&!u->battle.available)||!IsWindow(u->owner))return 0;u->visible=1;u->detail=0;SetWindowPos(u->window,HWND_TOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE|SWP_SHOWWINDOW);SetTimer(u->window,1,500,NULL);InvalidateRect(u->window,NULL,FALSE);return 1;}
int s14_report_ui_show(S14ReportUI *u,HINSTANCE instance,HWND owner,uintptr_t base,const wchar_t *root,const S14ReportSearch *search,const S14ReportBattle *battle){
    if(!u||!IsWindow(owner)||!root||wcslen(root)>=MAX_PATH||(!search&&!battle))return 0;S14ReportSearch s={0};S14ReportBattle b={0};if((search&&!s14_report_search_copy(&s,search))||(battle&&!s14_report_battle_copy(&b,battle))){s14_report_search_free(&s);s14_report_battle_free(&b);return 0;}if(s.available&&b.available&&(s.start!=b.start||s.end!=b.end||s.force!=b.force))s14_report_search_free(&s);if(u->window&&u->owner!=owner)s14_report_ui_destroy(u);u->owner=owner;u->instance=instance;u->base=base;wcscpy(u->root,root);if(!u->window&&!create(u,instance,owner)){s14_report_search_free(&s);s14_report_battle_free(&b);return 0;}s14_report_search_free(&u->search_data);s14_report_battle_free(&u->battle);u->search_data=s;u->battle=b;free(u->important);u->important=NULL;u->important_count=0;u->force_name[0]=0;if(b.line_count){u->important=calloc((size_t)b.line_count,sizeof(int));if(u->important)for(int i=b.line_count-1;i>=0;i--)if(b.lines[i].important)u->important[u->important_count++]=i;}identities(u);if(!u->portraits)u->portraits=s14_portrait_create(root);RECT client;POINT origin={0};if(!GetClientRect(owner,&client)||!ClientToScreen(owner,&origin))return 0;OffsetRect(&client,origin.x,origin.y);int width=client.right-client.left-px(u,30),height=client.bottom-client.top-px(u,30);if(width>px(u,1100))width=px(u,1100);if(height>px(u,790))height=px(u,790);if(width<px(u,420)||height<px(u,360))return 0;u->width=width;u->height=height;u->scroll=u->detail=u->detail_scroll=u->expanded=0;layout(u);u->visible=1;SetWindowPos(u->window,HWND_TOPMOST,client.left+(client.right-client.left-width)/2,client.top+(client.bottom-client.top-height)/2,width,height,SWP_NOACTIVATE|SWP_SHOWWINDOW);SetTimer(u->window,1,500,NULL);InvalidateRect(u->window,NULL,FALSE);UpdateWindow(u->window);return 1;
}
void s14_report_ui_tick(S14ReportUI *u,int foreground){if(!u||!u->window||!u->visible)return;if(!foreground||!IsWindowVisible(u->owner)||IsIconic(u->owner))ShowWindow(u->window,SW_HIDE);else if(!IsWindowVisible(u->window))SetWindowPos(u->window,HWND_TOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE|SWP_SHOWWINDOW);}
void s14_report_ui_destroy(S14ReportUI *u){if(!u)return;if(u->window){KillTimer(u->window,1);DestroyWindow(u->window);}HFONT list[]={u->title,u->name,u->body,u->small,u->number};for(int i=0;i<5;i++)if(list[i])DeleteObject(list[i]);s14_report_search_free(&u->search_data);s14_report_battle_free(&u->battle);free(u->important);s14_portrait_destroy(u->portraits);memset(u,0,sizeof(*u));}
